# FROM eclipse-temurin:17-jdk-alpine

# # Install required tools
# RUN apk add --no-cache curl unzip bash

# # Download and install SonarScanner CLI
# ENV SONAR_SCANNER_VERSION=4.7.0.2747
# RUN curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip && \
#     unzip sonar-scanner.zip && \
#     mv sonar-scanner-${SONAR_SCANNER_VERSION} /opt/sonar-scanner && \
#     ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner && \
#     rm -f sonar-scanner.zip

# ENV SONAR_SCANNER_HOME=/opt/sonar-scanner
# ENV PATH="${SONAR_SCANNER_HOME}/bin:${PATH}"

# ENTRYPOINT ["sonar-scanner"]
# --------------------------------------------------
# FROM eclipse-temurin:17-jdk as base

# ENV SONAR_SCANNER_VERSION=4.7.0.2747

# # Install sonar-scanner
# RUN apt-get update && apt-get install -y unzip wget && \
#     wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip && \
#     unzip sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip && \
#     mv sonar-scanner-${SONAR_SCANNER_VERSION} /opt/sonar-scanner && \
#     ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner && \
#     rm -rf sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip

# # Remove legacy or default task definitions if present
# RUN sed -i '/sonar.task/d' /opt/sonar-scanner/conf/sonar-scanner.properties

# ENV PATH="/opt/sonar-scanner/bin:$PATH"
# ENV SONAR_SCANNER_OPTS="-server"

# WORKDIR /usr/src
# ENTRYPOINT ["sonar-scanner"]
#-------------------------------------------------------------------

# FROM eclipse-temurin:17-jdk AS base

# ENV SONAR_SCANNER_VERSION=4.7.0.2747

# # Install sonar-scanner
# RUN apt-get update && apt-get install -y unzip wget && \
#     wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip && \
#     unzip sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip && \
#     mv sonar-scanner-${SONAR_SCANNER_VERSION} /opt/sonar-scanner && \
#     ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner && \
#     rm -rf sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip

# # Remove legacy or default task definitions if present
# RUN sed -i '/sonar.task/d' /opt/sonar-scanner/conf/sonar-scanner.properties

# ENV PATH="/opt/sonar-scanner/bin:$PATH"
# ENV SONAR_SCANNER_OPTS="-server"

# WORKDIR /usr/src
# ENTRYPOINT ["sonar-scanner"]

#-------------------------------------------------------------------

FROM eclipse-temurin:17-jdk

# Install required tools
RUN apt-get update && apt-get install -y unzip wget curl && \
    rm -rf /var/lib/apt/lists/*

# Install Sonar Scanner
ENV SONAR_SCANNER_VERSION=4.7.0.2747
RUN wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip && \
    unzip sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip && \
    mv sonar-scanner-${SONAR_SCANNER_VERSION} /opt/sonar-scanner && \
    ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner && \
    rm sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip

# Ensure JAVA_HOME and PATH are set
ENV JAVA_HOME=/opt/java/openjdk
ENV PATH=$JAVA_HOME/bin:/opt/sonar-scanner/bin:$PATH

# Set working directory
WORKDIR /usr/src

# Use shell so commands like -X etc. work
ENTRYPOINT ["sonar-scanner"]
